package taller

/*
 * This Scala source file was generated by the Gradle 'init' task.
 */


object App {
  def main(args: Array[String]): Unit = {
    val objSum =  new Sumatoria()
    //println(objSum.suma(1,0,5))
    println(objSum.opCurrificada("*")(2)(1)(1)(5))
    println(greeting())

  }

  def greeting(): String = "Hello, world!"
}
